config/routes.rb
Rails.application.routes.draw do
  root to: "pages#homepage"
  get 'homepage', to: 'pages#homepage'
  resources :trainers, only: [:show, :new, :create, :edit, :update]
  resources :pokemons, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :trainer
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokemon
end

app/models/trainer_pokemon.rb
class TrainerPokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :find_pokemon, only: [:show, :edit, :update]

  def index
    @pokemons = Pokemon.all
  end

  def show
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    if @pokemon.save
      redirect_to @pokemon
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pokemon.update(pokemon_params)
      redirect_to @pokemon
    else
      render 'edit'
    end
  end

  def find_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  def pokemon_params
    params.require(:pokemon).permit(:number, :name, :height, :weight, :type, :move_list, :ability_list)
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :find_trainer, only: [:show, :edit, :update]

  def show
  end

  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      redirect_to @trainer
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @trainer.update(trainer_params)
      redirect_to @trainer
    else
      render 'edit'
    end
  end

  def find_trainer
    @trainer = Trainer.find(params[:id])
  end

  def trainer_params
    params.require(:trainer).permit(:name, :age, :gender, :favourite_pokemon, :hometown)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonTrainerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Trainer", new_trainer_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/trainers/edit.html.erb
<%= simple_form_for @trainer do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :gender %>
  <%= f.input :favourite_pokemon %>
  <%= f.input :hometown %>
  <%= f.button :submit %>
<% end %>

app/views/trainers/new.html.erb
<%= simple_form_for @trainer do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :gender %>
  <%= f.input :favourite_pokemon %>
  <%= f.input :hometown %>
  <%= f.button :submit %>
<% end %>

app/views/trainers/show.html.erb
<div class="trainer-container">
  <div class="trainer-details">
    <strong>Trainer Details</strong>
    <ul class="trainer-details-list">
      <li><strong>Name:</strong> <%= @trainer.name %></li>
      <li><strong>Age:</strong> <%= @trainer.age %></li>
      <li><strong>Gender:</strong> <%= @trainer.gender %></li>
      <li><strong>Favourite Pokemon:</strong> <%= @trainer.favourite_pokemon %></li>
      <li><strong>Hometown:</strong> <%= @trainer.hometown %></li>
    </ul>
  </div>
  <div class="trainer-avatar">
    <%= image_tag("mikey-avatar", size: "300") %>
  </div>
  <div class="trainer-pokemon-list">
    <strong>Pokemon List</strong>
    <ul class="trainer-pokemon-list-list">
      <li>Charmander</li>
      <li>Pikachu</li>
      <li>Gengar</li>
      <li>Mew</li>
      <li>Bulbasaur</li>
      <li>Gloom</li>
    </ul>
  </div>
</div>